### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by peastman** [LTPV/LTPV#11]
I'm trying to install LTPV on Ubuntu 18.04.  When I run the command

```
./waf configure -m release
```

it fails with this error

```
Traceback (most recent call last):
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Scripting.py", line 98, in waf_entry_point
    run_commands()
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Scripting.py", line 155, in run_commands
    parse_options()
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Scripting.py", line 128, in parse_options
    Context.create_context('options').execute()
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Options.py", line 136, in execute
    super(OptionsContext,self).execute()
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Context.py", line 92, in execute
    self.recurse([os.path.dirname(g_module.root_path)])
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Context.py", line 133, in recurse
    user_function(self)
  File "/home/peastman/Downloads/LTPV/wscript", line 45, in options
    opt.load('compiler_c compiler_cxx doxygen boost')
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Context.py", line 89, in load
    fun(self)
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Tools/compiler_c.py", line 36, in options
    opt.load_special_tools('c_*.py',ban=['c_dumbpreproc.py'])
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Context.py", line 289, in load_special_tools
    lst=self.root.find_node(waf_dir).find_node('waflib/extras').ant_glob(var)
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Node.py", line 331, in ant_glob
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
  File "/home/peastman/Downloads/LTPV/.waf3-1.8.0-6bc34a5b7812916b2c8048506cfe77bb/waflib/Node.py", line 331, in <listcomp>
    ret=[x for x in self.ant_iter(accept=accept,pats=[to_pat(incl),to_pat(excl)],maxdepth=kw.get('maxdepth',25),dir=dir,src=src,remove=kw.get('remove',True))]
RuntimeError: generator raised StopIteration
```

**Comment by salehjg** [comment]
I used waf-lite in https://gitlab.com/ita1024/waf/tags (latest release)
Don't use the waf executable in this repository.
